### ISSUE TITLE
error while running container "RuntimeError: no running event loop"

### ISSUE THREAD

**Issue by csakthikumar** [KaitoKid/NestVideoBackup#3]
Hi @KaitoKid, Thanks for this amazing project. I am getting the below error when I create a container via compose file. Can you please help me with this?
```

2024-12-27 07:02:07,621 - tools - INFO - Welcome to the Google Nest Doorbell Local Storage Downloader
2024-12-27 07:02:07,621 - tools - INFO - Initializing the Google connection using the master_token
2024-12-27 07:02:07,621 - tools - INFO - Getting Camera Devices
2024-12-27 07:02:09,566 - tools - INFO - Found 1 Camera Device
2024-12-27 07:02:09,566 - tools - INFO - Initialized a Data Syncer
2024-12-27 07:02:09,571 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
Traceback (most recent call last):
  File "/app/main.py", line 85, in <module>
    main()
  File "/app/main.py", line 77, in main
    scheduler.start()
  File "/usr/local/lib/python3.12/site-packages/apscheduler/schedulers/asyncio.py", line 35, in start
    self._eventloop = asyncio.get_running_loop()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

```

**Comment by KaitoKid** [comment]
Unfortunately I don't have a battery doorbell anymore (I've transitioned to a wired one), but I'll take a look later this weekend.

**Comment by csakthikumar** [comment]
Thanks for reverting back. I am using a wired nest doorbell too. Let me know what I need to look for I will also give it a shot.

**Comment by csakthikumar** [comment]
@KaitoKid please let me know when we can look at the same. or please give me some pointers

**Comment by pdg82** [comment]
Hello @KaitoKid . I'm running into the same issue.

I've done some research, but not able to find a solution for this. 

Please let me know if you need more info, I'm more than willing to support or send info to you. 

```
2025-02-16 15:40:34,238 - tools - INFO - Welcome to the Google Nest Doorbell Local Storage Downloader
2025-02-16 15:40:34,239 - tools - INFO - Initializing the Google connection using the master_token
2025-02-16 15:40:34,239 - tools - INFO - Getting Camera Devices
2025-02-16 15:40:35,190 - tools - INFO - Found 1 Camera Device
2025-02-16 15:40:35,190 - tools - INFO - Initialized a Data Syncer
2025-02-16 15:40:35,192 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
Traceback (most recent call last):
  File "/home/petrus/nestie/NestVideoBackup/./main.py", line 85, in <module>
    main()
  File "/home/petrus/nestie/NestVideoBackup/./main.py", line 77, in main
    scheduler.start()
  File "/home/petrus/.local/lib/python3.12/site-packages/apscheduler/schedulers/asyncio.py", line 35, in start
    self._eventloop = asyncio.get_running_loop()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

```

**Comment by aschain** [comment]
I had to change the async scheduler part of main.py lines 69-82 to get it to work for me (in addition to adding pytz to requirements) to the following:

```
    # Create an event loop explicitly
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

    # Schedule the job to run every x minutes
    scheduler = AsyncIOScheduler(event_loop=loop)
    scheduler.add_job(
        sync_schedule,
        'interval',
        minutes=REFRESH_INTERVAL,
        next_run_time=datetime.datetime.now() + datetime.timedelta(seconds=10)
    )
    scheduler.start()

    try:
        loop.run_forever()
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        loop.close()
```

**Comment by csakthikumar** [comment]
@aschain fix is working fine I think it can be merged to master branch

**Comment by pdg82** [comment]
@aschain , @csakthikumar I can confirm this fix is working fine. Thanks!

**Comment by KaitoKid** [comment]
Thanks for the catch everyone

**Comment by csakthikumar** [comment]
fix is merged hence closing the issue
